//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQ_Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IQ_Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion1 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion10 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion10Answer1 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion10Answer1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion10Answer2 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion10Answer2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion10Answer3 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion10Answer3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion10Answer4 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion10Answer4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion11 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion11Answer1 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion11Answer1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion11Answer2 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion11Answer2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion11Answer3 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion11Answer3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion11Answer4 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion11Answer4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion12 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion12Answer1 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion12Answer1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion12Answer2 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion12Answer2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion12Answer3 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion12Answer3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion12Answer4 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion12Answer4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion13 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion13Answer1 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion13Answer1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion13Answer2 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion13Answer2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion13Answer3 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion13Answer3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion13Answer4 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion13Answer4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion14 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion14Answer1 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion14Answer1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion14Answer2 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion14Answer2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion14Answer3 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion14Answer3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion14Answer4 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion14Answer4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion15 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion15Answer1 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion15Answer1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion15Answer2 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion15Answer2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion15Answer3 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion15Answer3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion15Answer4 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion15Answer4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion16 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion16Answer1 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion16Answer1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion16Answer2 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion16Answer2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion16Answer3 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion16Answer3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion16Answer4 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion16Answer4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion17 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion17Answer1 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion17Answer1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion17Answer2 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion17Answer2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion17Answer3 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion17Answer3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion17Answer4 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion17Answer4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion18 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion18Answer1 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion18Answer1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion18Answer2 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion18Answer2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion18Answer3 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion18Answer3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion18Answer4 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion18Answer4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion19 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion19Answer1 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion19Answer1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion19Answer2 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion19Answer2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion19Answer3 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion19Answer3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion19Answer4 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion19Answer4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion1Answer1 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion1Answer1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion1Answer2 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion1Answer2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion1Answer3 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion1Answer3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion1Answer4 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion1Answer4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion2 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion20 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion20Answer1 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion20Answer1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion20Answer2 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion20Answer2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion20Answer3 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion20Answer3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion20Answer4 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion20Answer4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion2Answer1 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion2Answer1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion2Answer2 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion2Answer2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion2Answer3 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion2Answer3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion2Answer4 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion2Answer4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion3 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion3Answer1 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion3Answer1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion3Answer2 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion3Answer2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion3Answer3 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion3Answer3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion3Answer4 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion3Answer4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion4 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion4Answer1 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion4Answer1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion4Answer2 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion4Answer2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion4Answer3 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion4Answer3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion4Answer4 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion4Answer4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion5 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion5Answer1 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion5Answer1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion5Answer2 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion5Answer2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion5Answer3 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion5Answer3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion5Answer4 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion5Answer4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion6 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion6Answer1 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion6Answer1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion6Answer2 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion6Answer2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion6Answer3 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion6Answer3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion6Answer4 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion6Answer4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion7 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion7Answer1 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion7Answer1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion7Answer2 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion7Answer2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion7Answer3 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion7Answer3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion7Answer4 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion7Answer4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion8 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion8Answer1 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion8Answer1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion8Answer2 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion8Answer2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion8Answer3 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion8Answer3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion8Answer4 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion8Answer4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion9 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion9Answer1 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion9Answer1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion9Answer2 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion9Answer2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion9Answer3 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion9Answer3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgQuestion9Answer4 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion9Answer4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополни ја низата 25, 24, 22, 19, 15....
        /// </summary>
        internal static string TxtQuestion1 {
            get {
                return ResourceManager.GetString("TxtQuestion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополни ја низата 2, 3, 8, 63....
        /// </summary>
        internal static string TxtQuestion10 {
            get {
                return ResourceManager.GetString("TxtQuestion10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3968.
        /// </summary>
        internal static string TxtQuestion10Answer1 {
            get {
                return ResourceManager.GetString("TxtQuestion10Answer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3792.
        /// </summary>
        internal static string TxtQuestion10Answer2 {
            get {
                return ResourceManager.GetString("TxtQuestion10Answer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3381.
        /// </summary>
        internal static string TxtQuestion10Answer3 {
            get {
                return ResourceManager.GetString("TxtQuestion10Answer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3743.
        /// </summary>
        internal static string TxtQuestion10Answer4 {
            get {
                return ResourceManager.GetString("TxtQuestion10Answer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string TxtQuestion1Answer1 {
            get {
                return ResourceManager.GetString("TxtQuestion1Answer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        internal static string TxtQuestion1Answer2 {
            get {
                return ResourceManager.GetString("TxtQuestion1Answer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        internal static string TxtQuestion1Answer3 {
            get {
                return ResourceManager.GetString("TxtQuestion1Answer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string TxtQuestion1Answer4 {
            get {
                return ResourceManager.GetString("TxtQuestion1Answer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополни ја низата A, D, G, J __.
        /// </summary>
        internal static string TxtQuestion2 {
            get {
                return ResourceManager.GetString("TxtQuestion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string TxtQuestion2Answer1 {
            get {
                return ResourceManager.GetString("TxtQuestion2Answer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        internal static string TxtQuestion2Answer2 {
            get {
                return ResourceManager.GetString("TxtQuestion2Answer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O.
        /// </summary>
        internal static string TxtQuestion2Answer3 {
            get {
                return ResourceManager.GetString("TxtQuestion2Answer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        internal static string TxtQuestion2Answer4 {
            get {
                return ResourceManager.GetString("TxtQuestion2Answer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополни ја низата 2, 4, 16, 256, ....
        /// </summary>
        internal static string TxtQuestion3 {
            get {
                return ResourceManager.GetString("TxtQuestion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 65536.
        /// </summary>
        internal static string TxtQuestion3Answer1 {
            get {
                return ResourceManager.GetString("TxtQuestion3Answer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 66437.
        /// </summary>
        internal static string TxtQuestion3Answer2 {
            get {
                return ResourceManager.GetString("TxtQuestion3Answer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 66535.
        /// </summary>
        internal static string TxtQuestion3Answer3 {
            get {
                return ResourceManager.GetString("TxtQuestion3Answer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 65722.
        /// </summary>
        internal static string TxtQuestion3Answer4 {
            get {
                return ResourceManager.GetString("TxtQuestion3Answer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополни ја низата A, S, D, F, G....
        /// </summary>
        internal static string TxtQuestion4 {
            get {
                return ResourceManager.GetString("TxtQuestion4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        internal static string TxtQuestion4Answer1 {
            get {
                return ResourceManager.GetString("TxtQuestion4Answer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I.
        /// </summary>
        internal static string TxtQuestion4Answer2 {
            get {
                return ResourceManager.GetString("TxtQuestion4Answer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.
        /// </summary>
        internal static string TxtQuestion4Answer3 {
            get {
                return ResourceManager.GetString("TxtQuestion4Answer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.
        /// </summary>
        internal static string TxtQuestion4Answer4 {
            get {
                return ResourceManager.GetString("TxtQuestion4Answer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополни ја низата  1, 4, 9, 16, 25....
        /// </summary>
        internal static string TxtQuestion5 {
            get {
                return ResourceManager.GetString("TxtQuestion5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 42.
        /// </summary>
        internal static string TxtQuestion5Answer1 {
            get {
                return ResourceManager.GetString("TxtQuestion5Answer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 61.
        /// </summary>
        internal static string TxtQuestion5Answer2 {
            get {
                return ResourceManager.GetString("TxtQuestion5Answer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 36.
        /// </summary>
        internal static string TxtQuestion5Answer3 {
            get {
                return ResourceManager.GetString("TxtQuestion5Answer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29.
        /// </summary>
        internal static string TxtQuestion5Answer4 {
            get {
                return ResourceManager.GetString("TxtQuestion5Answer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополни ја низата 1, 1, 2, 3, 5....
        /// </summary>
        internal static string TxtQuestion6 {
            get {
                return ResourceManager.GetString("TxtQuestion6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        internal static string TxtQuestion6Answer1 {
            get {
                return ResourceManager.GetString("TxtQuestion6Answer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string TxtQuestion6Answer2 {
            get {
                return ResourceManager.GetString("TxtQuestion6Answer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string TxtQuestion6Answer3 {
            get {
                return ResourceManager.GetString("TxtQuestion6Answer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string TxtQuestion6Answer4 {
            get {
                return ResourceManager.GetString("TxtQuestion6Answer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополни ја низата 1, 8, 1, 4, 7, 0, 7, 0....
        /// </summary>
        internal static string TxtQuestion7 {
            get {
                return ResourceManager.GetString("TxtQuestion7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string TxtQuestion7Answer1 {
            get {
                return ResourceManager.GetString("TxtQuestion7Answer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string TxtQuestion7Answer2 {
            get {
                return ResourceManager.GetString("TxtQuestion7Answer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string TxtQuestion7Answer3 {
            get {
                return ResourceManager.GetString("TxtQuestion7Answer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string TxtQuestion7Answer4 {
            get {
                return ResourceManager.GetString("TxtQuestion7Answer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополни ја низата 1, 3, 6, 10, 15....
        /// </summary>
        internal static string TxtQuestion8 {
            get {
                return ResourceManager.GetString("TxtQuestion8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21.
        /// </summary>
        internal static string TxtQuestion8Answer1 {
            get {
                return ResourceManager.GetString("TxtQuestion8Answer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18.
        /// </summary>
        internal static string TxtQuestion8Answer2 {
            get {
                return ResourceManager.GetString("TxtQuestion8Answer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24.
        /// </summary>
        internal static string TxtQuestion8Answer3 {
            get {
                return ResourceManager.GetString("TxtQuestion8Answer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19.
        /// </summary>
        internal static string TxtQuestion8Answer4 {
            get {
                return ResourceManager.GetString("TxtQuestion8Answer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополни ја низата 1, 3, 4, 7, 11....
        /// </summary>
        internal static string TxtQuestion9 {
            get {
                return ResourceManager.GetString("TxtQuestion9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18.
        /// </summary>
        internal static string TxtQuestion9Answer1 {
            get {
                return ResourceManager.GetString("TxtQuestion9Answer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21.
        /// </summary>
        internal static string TxtQuestion9Answer2 {
            get {
                return ResourceManager.GetString("TxtQuestion9Answer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23.
        /// </summary>
        internal static string TxtQuestion9Answer3 {
            get {
                return ResourceManager.GetString("TxtQuestion9Answer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19.
        /// </summary>
        internal static string TxtQuestion9Answer4 {
            get {
                return ResourceManager.GetString("TxtQuestion9Answer4", resourceCulture);
            }
        }
    }
}
